import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { MainLayout } from '@/components/layout/MainLayout/MainLayout'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body>
				<MainLayout>{children}</MainLayout>
			</body>
		</html>
	)
}
